# Generated by Django 5.2.4 on 2025-08-11 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_produto_video_imagemproduto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
    ]
